WITH deduplicated_src  as (
      SELECT employee_code,
          employee_name,
          birth_day,
          mobile,
          email,
          job_title_id,
          job_title_name,
          position_id,
          position_name,
          concurrent_position_id,
          concurrent_position_name,
          unit_code,
          unit_id,
          start_date,
          created_date,
          updated_date,
          employee_status,
          official_date,
          end_date,
          internship_start_date,
          action_status,
          ROW_NUMBER() OVER (PARTITION BY employee_code ORDER BY updated_date, action_status DESC) as row_num
      FROM staging.{{ params.des_schema }}_{{ params.des_table }}
)

MERGE INTO {{ params.des_schema }}.{{ params.des_table }} as des
USING (
      SELECT employee_code,
          employee_name,
          birth_day,
          mobile,
          email,
          job_title_id,
          job_title_name,
          position_id,
          position_name,
          concurrent_position_id,
          concurrent_position_name,
          unit_code,
          unit_id,
          start_date,
          created_date,
          updated_date,
          employee_status,
          official_date,
          end_date,
          internship_start_date,
          action_status
      FROM deduplicated_src 
      WHERe row_num = 1
) as src

ON des.employee_code = src.employee_code
WHEN MATCHED THEN
    UPDATE SET 
              employee_code = src.employee_code,
              employee_name = src.employee_name,
              birth_day = src.birth_day,
              mobile = src.mobile,
              email = src.email,
              job_title_id = src.job_title_id,
              job_title_name = src.job_title_name,
              position_id = src.position_id,
              position_name = src.position_name,
              concurrent_position_id = src.concurrent_position_id,
              concurrent_position_name = src.concurrent_position_name,
              unit_code = src.unit_code,
              unit_id = src.unit_id,
              start_date = src.start_date,
              created_date = src.created_date,
              updated_date = src.updated_date,
              employee_status = src.employee_status,
              official_date = src.official_date,
              end_date = src.end_date,
              internship_start_date = src.internship_start_date,
              action_status = src.action_status
WHEN NOT MATCHED THEN
    INSERT (
          employee_code,
          employee_name,
          birth_day,
          mobile,
          email,
          job_title_id,
          job_title_name,
          position_id,
          position_name,
          concurrent_position_id,
          concurrent_position_name,
          unit_code,
          unit_id,
          start_date,
          created_date,
          updated_date,
          employee_status,
          official_date,
          end_date,
          internship_start_date,
          action_status
          )
    VALUES(
          src.employee_code,
          src.employee_name,
          src.birth_day,
          src.mobile,
          src.email,
          src.job_title_id,
          src.job_title_name,
          src.position_id,
          src.position_name,
          src.concurrent_position_id,
          src.concurrent_position_name,
          src.unit_code,
          src.unit_id,
          src.start_date,
          src.created_date,
          src.updated_date,
          src.employee_status,
          src.official_date,
          src.end_date,
          src.internship_start_date,
          src.action_status
          );
