MERGE INTO {{ params.des_schema }}.{{ params.des_table }} as des
USING staging.{{ params.des_schema }}_{{ params.des_table }} as src
ON des.mailstxnid = src.mailstxnid
   AND des.productcode = src.productcode
WHEN MATCHED THEN
    UPDATE SET
        amentryid = src.amentryid,
        poscode = src.poscode,
        type = src.type,
        service = src.service,
        servicecode = src.servicecode,
        packtype = src.packtype,
        material = src.material,
        postcode = src.postcode,
        address = src.address,
        fullname = src.fullname,
        phone = src.phone,
        email = src.email,
        days = src.days,
        invoicenumber = src.invoicenumber,
        invoiceissueddate = src.invoiceissueddate,
        codamount = src.codamount,
        doctype = src.doctype,
        docno = src.docno,
        quantity = src.quantity,
        feeamount = src.feeamount,
        taxcode = src.taxcode,
        taxrate = src.taxrate,
        vatamount = src.vatamount,
        account = src.account,
        feepublicamount = src.feepublicamount,
        vatpublicamount = src.vatpublicamount,
        poscode_bdt = src.poscode_bdt,
        createddate = src.createddate,
        created_date_id = src.created_date_id,
        entrytype = src.entrytype,
        feeamountorg = src.feeamountorg,
        feepublicamountorg = src.feepublicamountorg,
        vatamountorg = src.vatamountorg,
        vatpublicamountorg = src.vatpublicamountorg,
        totalprice = src.totalprice,
        update_date = src.update_date
WHEN NOT MATCHED THEN
    INSERT (
      id, 
      mailstxnid, 
      amentryid, 
      poscode, 
      type, 
      service, 
      servicecode, 
      productcode, 
      packtype, 
      material, 
      postcode, 
      address, 
      fullname,
      phone, 
      email, 
      days, 
      invoicenumber, 
      invoiceissueddate, 
      codamount, 
      doctype, 
      docno, 
      quantity, 
      feeamount, 
      taxcode, 
      taxrate, 
      vatamount, 
      account, 
      feepublicamount, 
      vatpublicamount, 
      poscode_bdt, 
      createddate, 
      created_date_id, 
      entrytype, 
      feeamountorg,
      feepublicamountorg, 
      vatamountorg, 
      vatpublicamountorg, 
      totalprice, 
      update_date
    )
    VALUES (
      src.id, src.mailstxnid, src.amentryid, src.poscode, src.type, src.service, src.servicecode, src.productcode, src.packtype, src.material, src.postcode, src.address, src.fullname, src.phone, src.email, src.days, src.invoicenumber, src.invoiceissueddate, src.codamount, src.doctype, src.docno, src.quantity, src.feeamount, src.taxcode, src.taxrate, src.vatamount, src.account, src.feepublicamount, src.vatpublicamount, src.poscode_bdt, src.createddate, src.created_date_id, src.entrytype, src.feeamountorg, src.feepublicamountorg, src.vatamountorg, src.vatpublicamountorg, src.totalprice, src.update_date
    );
