MERGE INTO {{ params.des_schema }}.{{ params.des_table }} as des
USING staging.{{ params.des_schema }}_{{ params.des_table }} as src
ON (des.mailstxnid = src.mailstxnid)
    WHEN MATCHED THEN
    UPDATE SET 
        amentryid = src.amentryid,
        poscode = src.poscode,
        posprovincecode = src.posprovincecode,
        typename = src.typename,
        service = src.service,
        servicecode = src.servicecode,
        productcode = src.productcode,
        servicecaption = src.servicecaption,
        ttnumber = src.ttnumber,
        type = src.type,
        sortingcode = src.sortingcode,
        podelivery = src.podelivery,
        zone = src.zone,
        quantity = src.quantity,
        unit = src.unit,
        weight = src.weight,
        priceweight = src.priceweight,
        dimweight = src.dimweight,
        height = src.height,
        length = src.length,
        width = src.width,
        country = src.country,
        senderphone = src.senderphone,
        senderfullname = src.senderfullname,
        senderemail = src.senderemail,
        senderaddress = src.senderaddress,
        senderpostcode = src.senderpostcode,
        senderprovincecode = src.senderprovincecode,
        senderprovincename = src.senderprovincename,
        senderdistrictcode = src.senderdistrictcode,
        sendercommunecode = src.sendercommunecode,
        senderidnumber = src.senderidnumber,
        sendercontact = src.sendercontact,
        sendertaxcode = src.sendertaxcode,
        receiverphone = src.receiverphone,
        receiverfullname = src.receiverfullname,
        receiveremail = src.receiveremail,
        receiveraddress = src.receiveraddress,
        receiverpostcode = src.receiverpostcode,
        receiverprovincecode = src.receiverprovincecode,
        receiverprovincename = src.receiverprovincename,
        receiverdistrictcode = src.receiverdistrictcode,
        receivercommunecode = src.receivercommunecode,
        receiveridnumber = src.receiveridnumber,
        receivercontact = src.receivercontact,
        receivercity = src.receivercity,
        receivercountrycode = src.receivercountrycode,
        isoversized = src.isoversized,
        isfragile = src.isfragile,
        island = src.island,
        instructionwnd = src.instructionwnd,
        givebackaddress = src.givebackaddress,
        givebackpostcode = src.givebackpostcode,
        givebackphone = src.givebackphone,
        givebackcontactname = src.givebackcontactname,
        returnbeforedate = src.returnbeforedate,
        originposphone = src.originposphone,
        instructionbuss = src.instructionbuss,
        transportation = src.transportation,
        givebacktransportation = src.givebacktransportation,
        shipmenttype = src.shipmenttype,
        exporttype = src.exporttype,
        otherexporttype = src.otherexporttype,
        attachdocumenttype = src.attachdocumenttype,
        invoiceinfo = src.invoiceinfo,
        licenseinfo = src.licenseinfo,
        certificateinfo = src.certificateinfo,
        otherinfo = src.otherinfo,
        exchangerate = src.exchangerate,
        ccycode = src.ccycode,
        parcelcontents = src.parcelcontents,
        basicamount = src.basicamount,
        taxcode = src.taxcode,
        taxrate = src.taxrate,
        vatamount = src.vatamount,
        totalvat = src.totalvat,
        totalamount = src.totalamount,
        groupid = src.groupid,
        createdby = src.createdby,
        createddate = src.createddate,
        created_date_id = src.created_date_id,
        ttnumberawb = src.ttnumberawb,
        sendercustomercode = src.sendercustomercode,
        sendercontractcode = src.sendercontractcode,
        sendercustomertype = src.sendercustomertype,
        receivercustomercode = src.receivercustomercode,
        receivercontractcode = src.receivercontractcode,
        receivercustomertype = src.receivercustomertype,
        dispatchid = src.dispatchid,
        account = src.account,
        vataccount = src.vataccount,
        basicpublicamount = src.basicpublicamount,
        vatpublicamount = src.vatpublicamount,
        totalpublicvat = src.totalpublicvat,
        totalpublicamount = src.totalpublicamount,
        reason = src.reason,
        affairtype = src.affairtype,
        poscode_bdt = src.poscode_bdt,
        mailstxnidorg = src.mailstxnidorg,
        reasoncontent = src.reasoncontent,
        entrytype = src.entrytype,
        vatentrytype = src.vatentrytype,
        poscodeorg = src.poscodeorg,
        customerid = src.customerid,
        contractid = src.contractid,
        contracttype = src.contracttype,
        contracttypeid = src.contracttypeid,
        totalquantity = src.totalquantity,
        totalpieces = src.totalpieces,
        basicamountorg = src.basicamountorg,
        basicpublicamountorg = src.basicpublicamountorg,
        vatamountorg = src.vatamountorg,
        vatpublicamountorg = src.vatpublicamountorg,
        totalvatorg = src.totalvatorg,
        totalpublicvatorg = src.totalpublicvatorg,
        iscod = src.iscod,
        isc = src.isc,
        adjustmenttype = src.adjustmenttype,
        affaircontent = src.affaircontent,
        systemname = src.systemname,
        systemcustomerid = src.systemcustomerid,
        crmcode = src.crmcode,
        sendersystemname = src.sendersystemname,
        sendersystemcustomerid = src.sendersystemcustomerid,
        sendercrmcode = src.sendercrmcode,
        receiversystemname = src.receiversystemname,
        receiversystemcustomerid = src.receiversystemcustomerid,
        receivercrmcode = src.receivercrmcode,
        update_date = src.update_date
WHEN NOT MATCHED THEN
    INSERT (
        mailstxnid,
        amentryid,
        poscode,
        posprovincecode,
        typename,
        service,
        servicecode,
        productcode,
        servicecaption,
        ttnumber,
        type,
        sortingcode,
        podelivery,
        zone,
        quantity,
        unit,
        weight,
        priceweight,
        dimweight,
        height,
        length,
        width,
        country,
        senderphone,
        senderfullname,
        senderemail,
        senderaddress,
        senderpostcode,
        senderprovincecode,
        senderprovincename,
        senderdistrictcode,
        sendercommunecode,
        senderidnumber,
        sendercontact,
        sendertaxcode,
        receiverphone,
        receiverfullname,
        receiveremail,
        receiveraddress,
        receiverpostcode,
        receiverprovincecode,
        receiverprovincename,
        receiverdistrictcode,
        receivercommunecode,
        receiveridnumber,
        receivercontact,
        receivercity,
        receivercountrycode,
        isoversized,
        isfragile,
        island,
        instructionwnd,
        givebackaddress,
        givebackpostcode,
        givebackphone,
        givebackcontactname,
        returnbeforedate,
        originposphone,
        instructionbuss,
        transportation,
        givebacktransportation,
        shipmenttype,
        exporttype,
        otherexporttype,
        attachdocumenttype,
        invoiceinfo,
        licenseinfo,
        certificateinfo,
        otherinfo,
        exchangerate,
        ccycode,
        parcelcontents,
        basicamount,
        taxcode,
        taxrate,
        vatamount,
        totalvat,
        totalamount,
        groupid,
        createdby,
        createddate,
        created_date_id,
        ttnumberawb,
        sendercustomercode,
        sendercontractcode,
        sendercustomertype,
        receivercustomercode,
        receivercontractcode,
        receivercustomertype,
        dispatchid,
        account,
        vataccount,
        basicpublicamount,
        vatpublicamount,
        totalpublicvat,
        totalpublicamount,
        reason,
        affairtype,
        poscode_bdt,
        mailstxnidorg,
        reasoncontent,
        entrytype,
        vatentrytype,
        poscodeorg,
        customerid,
        contractid,
        contracttype,
        contracttypeid,
        totalquantity,
        totalpieces,
        basicamountorg,
        basicpublicamountorg,
        vatamountorg,
        vatpublicamountorg,
        totalvatorg,
        totalpublicvatorg,
        iscod,
        isc,
        adjustmenttype,
        affaircontent,
        systemname,
        systemcustomerid,
        crmcode,
        sendersystemname,
        sendersystemcustomerid,
        sendercrmcode,
        receiversystemname,
        receiversystemcustomerid,
        receivercrmcode,
        update_date
    )
    VALUES (
        src.mailstxnid,
        src.amentryid,
        src.poscode,
        src.posprovincecode,
        src.typename,
        src.service,
        src.servicecode,
        src.productcode,
        src.servicecaption,
        src.ttnumber,
        src.type,
        src.sortingcode,
        src.podelivery,
        src.zone,
        src.quantity,
        src.unit,
        src.weight,
        src.priceweight,
        src.dimweight,
        src.height,
        src.length,
        src.width,
        src.country,
        src.senderphone,
        src.senderfullname,
        src.senderemail,
        src.senderaddress,
        src.senderpostcode,
        src.senderprovincecode,
        src.senderprovincename,
        src.senderdistrictcode,
        src.sendercommunecode,
        src.senderidnumber,
        src.sendercontact,
        src.sendertaxcode,
        src.receiverphone,
        src.receiverfullname,
        src.receiveremail,
        src.receiveraddress,
        src.receiverpostcode,
        src.receiverprovincecode,
        src.receiverprovincename,
        src.receiverdistrictcode,
        src.receivercommunecode,
        src.receiveridnumber,
        src.receivercontact,
        src.receivercity,
        src.receivercountrycode,
        src.isoversized,
        src.isfragile,
        src.island,
        src.instructionwnd,
        src.givebackaddress,
        src.givebackpostcode,
        src.givebackphone,
        src.givebackcontactname,
        src.returnbeforedate,
        src.originposphone,
        src.instructionbuss,
        src.transportation,
        src.givebacktransportation,
        src.shipmenttype,
        src.exporttype,
        src.otherexporttype,
        src.attachdocumenttype,
        src.invoiceinfo,
        src.licenseinfo,
        src.certificateinfo,
        src.otherinfo,
        src.exchangerate,
        src.ccycode,
        src.parcelcontents,
        src.basicamount,
        src.taxcode,
        src.taxrate,
        src.vatamount,
        src.totalvat,
        src.totalamount,
        src.groupid,
        src.createdby,
        src.createddate,
        src.created_date_id,
        src.ttnumberawb,
        src.sendercustomercode,
        src.sendercontractcode,
        src.sendercustomertype,
        src.receivercustomercode,
        src.receivercontractcode,
        src.receivercustomertype,
        src.dispatchid,
        src.account,
        src.vataccount,
        src.basicpublicamount,
        src.vatpublicamount,
        src.totalpublicvat,
        src.totalpublicamount,
        src.reason,
        src.affairtype,
        src.poscode_bdt,
        src.mailstxnidorg,
        src.reasoncontent,
        src.entrytype,
        src.vatentrytype,
        src.poscodeorg,
        src.customerid,
        src.contractid,
        src.contracttype,
        src.contracttypeid,
        src.totalquantity,
        src.totalpieces,
        src.basicamountorg,
        src.basicpublicamountorg,
        src.vatamountorg,
        src.vatpublicamountorg,
        src.totalvatorg,
        src.totalpublicvatorg,
        src.iscod,
        src.isc,
        src.adjustmenttype,
        src.affaircontent,
        src.systemname,
        src.systemcustomerid,
        src.crmcode,
        src.sendersystemname,
        src.sendersystemcustomerid,
        src.sendercrmcode,
        src.receiversystemname,
        src.receiversystemcustomerid,
        src.receivercrmcode,
        src.update_date
    );
