MERGE INTO {{ params.des_schema }}.{{ params.des_table }} as des
USING staging.{{ params.des_schema }}_{{ params.des_table }} as src
ON (des.product_service_code = src.product_service_code)
    WHEN MATCHED THEN
    UPDATE SET 
        product_service_name = src.product_service_name,
        service_group_code = src.service_group_code,
        service_group_name = src.service_group_name,
        business_code = src.business_code,
        service_type = src.service_type,
        status = src.status,
        idx_l1 = src.idx_l1,
        item_l1_code = src.item_l1_code,
        item_l1_name = src.item_l1_name,
        ord_l1 = src.ord_l1,
        idx_l2 = src.idx_l2,
        item_l2_code = src.item_l2_code,
        item_l2_name = src.item_l2_name,
        ord_l2 = src.ord_l2,
        idx_l3 = src.idx_l3,
        item_l3_code = src.item_l3_code,
        item_l3_name = src.item_l3_name,
        ord_l3 = src.ord_l3,
        idx_l4 = src.idx_l4,
        item_l4_code = src.item_l4_code,
        item_l4_name = src.item_l4_name,
        ord_l4 = src.ord_l4,
        rule_type = src.rule_type,
        ord = src.ord,
        note = src.note
WHEN NOT MATCHED THEN
    INSERT (
        product_service_code,
        product_service_name,
        service_group_code,
        service_group_name,
        business_code,
        service_type,
        status,
        idx_l1,
        item_l1_code,
        item_l1_name,
        ord_l1,
        idx_l2,
        item_l2_code,
        item_l2_name,
        ord_l2,
        idx_l3,
        item_l3_code,
        item_l3_name,
        ord_l3,
        idx_l4,
        item_l4_code,
        item_l4_name,
        ord_l4,
        rule_type,
        ord,
        note
    )
    VALUES (
        src.product_service_code,
        src.product_service_name,
        src.service_group_code,
        src.service_group_name,
        src.business_code,
        src.service_type,
        src.status,
        src.idx_l1,
        src.item_l1_code,
        src.item_l1_name,
        src.ord_l1,
        src.idx_l2,
        src.item_l2_code,
        src.item_l2_name,
        src.ord_l2,
        src.idx_l3,
        src.item_l3_code,
        src.item_l3_name,
        src.ord_l3,
        src.idx_l4,
        src.item_l4_code,
        src.item_l4_name,
        src.ord_l4,
        src.rule_type,
        src.ord,
        src.note
    );

