MERGE INTO {{ params.des_schema }}.{{ params.des_table }} as des
USING staging.{{ params.des_schema }}_{{ params.des_table }} as src
ON (des.txnid = src.txnid)
    WHEN MATCHED THEN
    UPDATE SET 
        typename = src.typename,
        poscode = src.poscode,
        service = src.service,
        servicecode = src.servicecode,
        productcode = src.productcode,
        servicename = src.servicename,
        stamptype = src.stamptype,
        country = src.country,
        zone = src.zone,
        unit = src.unit,
        weight = src.weight,
        priceweight = src.priceweight,
        quantity = src.quantity,
        basicamount = src.basicamount,
        taxrate = src.taxrate,
        vatamount = src.vatamount,
        totalamount = src.totalamount,
        groupid = src.groupid,
        createdby = src.createdby,
        createddate = src.createddate,
        account = src.account,
        vataccount = src.vataccount,
        sessionid = src.sessionid,
        created_date_id = src.created_date_id,
        poscode_bdt = src.poscode_bdt,
        update_date = src.update_date
WHEN NOT MATCHED THEN
    INSERT (
        txnid,
        typename,
        poscode,
        service,
        servicecode,
        productcode,
        servicename,
        stamptype,
        country,
        zone,
        unit,
        weight,
        priceweight,
        quantity,
        basicamount,
        taxrate,
        vatamount,
        totalamount,
        groupid,
        createdby,
        createddate,
        account,
        vataccount,
        sessionid,
        created_date_id,
        poscode_bdt,
        update_date
    )
    VALUES (
        src.txnid,
        src.typename,
        src.poscode,
        src.service,
        src.servicecode,
        src.productcode,
        src.servicename,
        src.stamptype,
        src.country,
        src.zone,
        src.unit,
        src.weight,
        src.priceweight,
        src.quantity,
        src.basicamount,
        src.taxrate,
        src.vatamount,
        src.totalamount,
        src.groupid,
        src.createdby,
        src.createddate,
        src.account,
        src.vataccount,
        src.sessionid,
        src.created_date_id,
        src.poscode_bdt,
        src.update_date
    );
