MERGE INTO {{ params.des_schema }}.{{ params.des_table }} as des
USING staging.{{ params.des_schema }}_{{ params.des_table }} as src
ON (des.tran_id = src.tran_id and des.tran_id_org = src.tran_id_org and des.row_item_code = src.row_item_code)
    WHEN MATCHED THEN
    UPDATE SET 
        tran_date_id = src.tran_date_id,
        bdt_code = src.bdt_code,
        post_code = src.post_code,
        data_source = src.data_source,
        row_item_code = src.row_item_code,
        ma_spdv = src.ma_spdv,
        tran_code = src.tran_code,
        created_by = src.created_by,
        unit_price = src.unit_price,
        customer_phone = src.customer_phone,
        customer_id_num = src.customer_id_num,
        ma_doanhthu_ps = src.ma_doanhthu_ps,
        tinhchat_gd = src.tinhchat_gd,
        customer_group_id = src.customer_group_id,
        customer_email = src.customer_email,
        customer_bankacc = src.customer_bankacc,
        customer_add = src.customer_add,
        customer_name = src.customer_name,
        customerid = src.customerid,
        contractid = src.contractid,
        customer_type_id = src.customer_type_id,
        payment = src.payment,
        created_date = src.created_date,
        currency_code = src.currency_code,
        updated_date_id = src.updated_date_id,
        ma_loaigd = src.ma_loaigd,
        ma_doanh_thu = src.ma_doanh_thu,
        source = src.source,
        business_code = src.business_code,
        clue_payment = src.clue_payment,
        tax_declaration_code = src.tax_declaration_code,
        tax_rate_code = src.tax_rate_code,
        tran_id_org = src.tran_id_org,
        is_ctv_dl = src.is_ctv_dl,
        tran_month_id = src.tran_month_id,
        tran_updated_date_id = src.tran_updated_date_id,
        is_cod = src.is_cod,
        nhom_spdv = src.nhom_spdv,
        ma_kh_cha = src.ma_kh_cha,
        tran_year_id = src.tran_year_id,
        ty_le_ck = src.ty_le_ck,
        tran_period = src.tran_period,
        country = src.country,
        zone = src.zone,
        s98_cit_01 = src.s98_cit_01,
        s98_cit_03 = src.s98_cit_03,
        s98_cit_05 = src.s98_cit_05,
        s98_cit_07 = src.s98_cit_07,
        s98_cit_08 = src.s98_cit_08,
        s98_cit_10 = src.s98_cit_10,
        s98_cit_12 = src.s98_cit_12,
        s98_cit_14 = src.s98_cit_14,
        s98_cit_15 = src.s98_cit_15,
        s98_cit_16 = src.s98_cit_16,
        s98_cit_17 = src.s98_cit_17,
        s98_cit_18 = src.s98_cit_18,
        s98_cit_20 = src.s98_cit_20,
        s98_cit_21 = src.s98_cit_21,
        s98_cit_22 = src.s98_cit_22,
        s98_cit_23 = src.s98_cit_23,
        s98_cit_24 = src.s98_cit_24,
        s98_cit_25 = src.s98_cit_25,
        s98_cit_26 = src.s98_cit_26,
        weight = src.weight,
        weight_tc = src.weight_tc
WHEN NOT MATCHED THEN
    INSERT (
        tran_date_id,
        bdt_code,
        post_code,
        data_source,
        row_item_code,
        ma_spdv,
        tran_id,
        tran_code,
        created_by,
        unit_price,
        customer_phone,
        customer_id_num,
        ma_doanhthu_ps,
        tinhchat_gd,
        customer_group_id,
        customer_email,
        customer_bankacc,
        customer_add,
        customer_name,
        customerid,
        contractid,
        customer_type_id,
        payment,
        created_date,
        currency_code,
        updated_date_id,
        ma_loaigd,
        ma_doanh_thu,
        source,
        business_code,
        clue_payment,
        tax_declaration_code,
        tax_rate_code,
        tran_id_org,
        is_ctv_dl,
        tran_month_id,
        tran_updated_date_id,
        is_cod,
        nhom_spdv,
        ma_kh_cha,
        tran_year_id,
        ty_le_ck,
        tran_period,
        country,
        zone,
        s98_cit_01,
        s98_cit_03,
        s98_cit_05,
        s98_cit_07,
        s98_cit_08,
        s98_cit_10,
        s98_cit_12,
        s98_cit_14,
        s98_cit_15,
        s98_cit_16,
        s98_cit_17,
        s98_cit_18,
        s98_cit_20,
        s98_cit_21,
        s98_cit_22,
        s98_cit_23,
        s98_cit_24,
        s98_cit_25,
        s98_cit_26,
        weight,
        weight_tc
    )
    VALUES (
        src.tran_date_id,
        src.bdt_code,
        src.post_code,
        src.data_source,
        src.row_item_code,
        src.ma_spdv,
        src.tran_id,
        src.tran_code,
        src.created_by,
        src.unit_price,
        src.customer_phone,
        src.customer_id_num,
        src.ma_doanhthu_ps,
        src.tinhchat_gd,
        src.customer_group_id,
        src.customer_email,
        src.customer_bankacc,
        src.customer_add,
        src.customer_name,
        src.customerid,
        src.contractid,
        src.customer_type_id,
        src.payment,
        src.created_date,
        src.currency_code,
        src.updated_date_id,
        src.ma_loaigd,
        src.ma_doanh_thu,
        src.source,
        src.business_code,
        src.clue_payment,
        src.tax_declaration_code,
        src.tax_rate_code,
        src.tran_id_org,
        src.is_ctv_dl,
        src.tran_month_id,
        src.tran_updated_date_id,
        src.is_cod,
        src.nhom_spdv,
        src.ma_kh_cha,
        src.tran_year_id,
        src.ty_le_ck,
        src.tran_period,
        src.country,
        src.zone,
        src.s98_cit_01,
        src.s98_cit_03,
        src.s98_cit_05,
        src.s98_cit_07,
        src.s98_cit_08,
        src.s98_cit_10,
        src.s98_cit_12,
        src.s98_cit_14,
        src.s98_cit_15,
        src.s98_cit_16,
        src.s98_cit_17,
        src.s98_cit_18,
        src.s98_cit_20,
        src.s98_cit_21,
        src.s98_cit_22,
        src.s98_cit_23,
        src.s98_cit_24,
        src.s98_cit_25,
        src.s98_cit_26,
        src.weight,
        src.weight_tc
    );
