MERGE INTO {{ params.des_schema }}.{{ params.des_table }} as des
USING staging.{{ params.des_schema }}_{{ params.des_table }} as src
ON (des.row_item_code = src.row_item_code)
    WHEN MATCHED THEN
    UPDATE SET 
        report_code = src.report_code,
        row_item_name = src.row_item_name,
        row_parent_code = src.row_parent_code,
        factor = src.factor,
        font_size = src.font_size,
        font_style = src.font_style,
        stt = src.stt,
        idx = src.idx,
        dvt = src.dvt,
        condition_type = src.condition_type,
        status = src.status,
        source = src.source,
        nhom_nghiep_vu = src.nhom_nghiep_vu,
        is_nhap_tay = src.is_nhap_tay,
        cap = src.cap,
        is_ctv_dl = src.is_ctv_dl,
        ma_nv_tt_thuchiho = src.ma_nv_tt_thuchiho,
        ma_nv_tt_tienthu = src.ma_nv_tt_tienthu,
        ma_chuthe_thu = src.ma_chuthe_thu,
        ma_chuthe_chi = src.ma_chuthe_chi,
        ma_ton_quy_thu = src.ma_ton_quy_thu,
        ma_ton_quy_chi = src.ma_ton_quy_chi,
        ma_dong_tien_thu = src.ma_dong_tien_thu,
        ma_dong_tien_chi = src.ma_dong_tien_chi,
        ma_daumoi_thanhtoan = src.ma_daumoi_thanhtoan,
        ma_doitac = src.ma_doitac,
        hinhthuc_giaonhan_noptien = src.hinhthuc_giaonhan_noptien,
        ma_dtpc = src.ma_dtpc,
        item_code_show = src.item_code_show,
        is_dtpc = src.is_dtpc,
        ma_kk_thue = src.ma_kk_thue,
        enable_item = src.enable_item,
        enable_sl = src.enable_sl,
        enable_thuesuat = src.enable_thuesuat,
        is_phan_iii = src.is_phan_iii,
        is_parent = src.is_parent,
        is_hiden_item = src.is_hiden_item,
        is_nhap_dukiennam = src.is_nhap_dukiennam,
        nhom_chitieu = src.nhom_chitieu,
        ma_spdv = src.ma_spdv
WHEN NOT MATCHED THEN
    INSERT (
        report_code,
        row_item_code,
        row_item_name,
        row_parent_code,
        factor,
        font_size,
        font_style,
        stt,
        idx,
        dvt,
        condition_type,
        status,
        source,
        nhom_nghiep_vu,
        is_nhap_tay,
        cap,
        is_ctv_dl,
        ma_nv_tt_thuchiho,
        ma_nv_tt_tienthu,
        ma_chuthe_thu,
        ma_chuthe_chi,
        ma_ton_quy_thu,
        ma_ton_quy_chi,
        ma_dong_tien_thu,
        ma_dong_tien_chi,
        ma_daumoi_thanhtoan,
        ma_doitac,
        hinhthuc_giaonhan_noptien,
        ma_dtpc,
        item_code_show,
        is_dtpc,
        ma_kk_thue,
        enable_item,
        enable_sl,
        enable_thuesuat,
        is_phan_iii,
        is_parent,
        is_hiden_item,
        is_nhap_dukiennam,
        nhom_chitieu,
        ma_spdv
    )
    VALUES (
        src.report_code,
        src.row_item_code,
        src.row_item_name,
        src.row_parent_code,
        src.factor,
        src.font_size,
        src.font_style,
        src.stt,
        src.idx,
        src.dvt,
        src.condition_type,
        src.status,
        src.source,
        src.nhom_nghiep_vu,
        src.is_nhap_tay,
        src.cap,
        src.is_ctv_dl,
        src.ma_nv_tt_thuchiho,
        src.ma_nv_tt_tienthu,
        src.ma_chuthe_thu,
        src.ma_chuthe_chi,
        src.ma_ton_quy_thu,
        src.ma_ton_quy_chi,
        src.ma_dong_tien_thu,
        src.ma_dong_tien_chi,
        src.ma_daumoi_thanhtoan,
        src.ma_doitac,
        src.hinhthuc_giaonhan_noptien,
        src.ma_dtpc,
        src.item_code_show,
        src.is_dtpc,
        src.ma_kk_thue,
        src.enable_item,
        src.enable_sl,
        src.enable_thuesuat,
        src.is_phan_iii,
        src.is_parent,
        src.is_hiden_item,
        src.is_nhap_dukiennam,
        src.nhom_chitieu,
        src.ma_spdv
    );
