MERGE INTO {{ params.des_schema_name }}.{{ params.des_table_name }} des
USING staging.{{ params.des_schema_name }}_{{ params.des_table_name }} src
ON des.ID = src.ID
WHEN MATCHED AND src.UPDATE_DATE >= des.UPDATE_DATE THEN
    UPDATE SET
        CUSTOMER_CODE = src.CUSTOMER_CODE,
        CUSTOMER_NAME = src.CUSTOMER_NAME,
        CUSTOMER_PHONE = src.CUSTOMER_PHONE,
        CUSTOMER_PROVINCE_CODE = src.CUSTOMER_PROVINCE_CODE,
        CUSTOMER_DISTRICT_CODE = src.CUSTOMER_DISTRICT_CODE,
        CUSTOMER_COMMUNE_CODE = src.CUSTOMER_COMMUNE_CODE,
        CUSTOMER_POSTCODE = src.CUSTOMER_POSTCODE,
        CUSTOMER_EMAIL = src.CUSTOMER_EMAIL,
        CUSTOMER_ADD = src.CUSTOMER_ADD,
        SHIPMENT_CODE = src.SHIPMENT_CODE,
        CUSTOMER_CONTRACT_NUMBER = src.CUSTOMER_CONTRACT_NUMBER,
        CREATE_DATE = src.CREATE_DATE,
        UPDATE_DATE = src.UPDATE_DATE,
        USERNAME = src.USERNAME,
        POCODE = src.POCODE,
        STATUS = src.STATUS,
        SOURCE = src.SOURCE,
        PAYNOW = src.PAYNOW,
        PAYMENT = src.PAYMENT,
        ORDER_CODE = src.ORDER_CODE,
        ACCEPT_DATE = src.ACCEPT_DATE,
        ISAUTOGEN = src.ISAUTOGEN,
        ISAUTOADD = src.ISAUTOADD,
        ORG_CODE = src.ORG_CODE,
        BD2_NUM = src.BD2_NUM,
        CONTACT_NAME = src.CONTACT_NAME,
        TAX_CODE = src.TAX_CODE,
        IDENTIFY_NUM = src.IDENTIFY_NUM,
        TRANS_TYPE = src.TRANS_TYPE,
        ISDOMESTIC = src.ISDOMESTIC,
        KT1 = src.KT1,
        PROCESS_DATE = src.PROCESS_DATE,
        CASE_ID = src.CASE_ID,
        VER = src.VER,
        REPLACE_BY_ID = src.REPLACE_BY_ID,
        ORIGINAL_ID = src.ORIGINAL_ID,
        CONTRACT_SERVICE_CODE = src.CONTRACT_SERVICE_CODE,
        CUSTOMER_CODE_CRM = src.CUSTOMER_CODE_CRM,
        CUSTOMER_CODE_REF = src.CUSTOMER_CODE_REF,
        BDT_CODE = src.BDT_CODE,
        DELIVERY_INSTRUCTION = src.DELIVERY_INSTRUCTION,
        IS_PRINT = src.IS_PRINT,
        CUSTOMER_TYPE = src.CUSTOMER_TYPE,
        VERSION_LOCK = src.VERSION_LOCK,
        ISAUTOUPDATESENDER = src.ISAUTOUPDATESENDER,
        IS_PACKAGE_NORMAL = src.IS_PACKAGE_NORMAL,
        IS_PUBLIC_POSTAL = src.IS_PUBLIC_POSTAL,
        DOCUMENT_TYPE = src.DOCUMENT_TYPE,
        DOCUMENT_NAME = src.DOCUMENT_NAME,
        DOCUMENT_NUMBER = src.DOCUMENT_NUMBER,
        DOCUMENT_PROVIDE_DATE = src.DOCUMENT_PROVIDE_DATE,
        DOCUMENT_PROVIDE_ADDRESS = src.DOCUMENT_PROVIDE_ADDRESS,
        SOURCE_SYSTEM = src.SOURCE_SYSTEM,
        GROUP_TYPE = src.GROUP_TYPE,
        ORG_CODE_CREATE = src.ORG_CODE_CREATE,
        USERNAME_CREATE = src.USERNAME_CREATE,
        CUSTOMER_VPOSTCODE = src.CUSTOMER_VPOSTCODE,
        CUSTOMER_LAT = src.CUSTOMER_LAT,
        CUSTOMER_LNG = src.CUSTOMER_LNG
WHEN NOT MATCHED THEN
    INSERT (
        ID,
        CUSTOMER_CODE,
        CUSTOMER_NAME,
        CUSTOMER_PHONE,
        CUSTOMER_PROVINCE_CODE,
        CUSTOMER_DISTRICT_CODE,
        CUSTOMER_COMMUNE_CODE,
        CUSTOMER_POSTCODE,
        CUSTOMER_EMAIL,
        CUSTOMER_ADD,
        SHIPMENT_CODE,
        CUSTOMER_CONTRACT_NUMBER,
        CREATE_DATE,
        UPDATE_DATE,
        USERNAME,
        POCODE,
        STATUS,
        SOURCE,
        PAYNOW,
        PAYMENT,
        ORDER_CODE,
        ACCEPT_DATE,
        ISAUTOGEN,
        ISAUTOADD,
        ORG_CODE,
        BD2_NUM,
        CONTACT_NAME,
        TAX_CODE,
        IDENTIFY_NUM,
        TRANS_TYPE,
        ISDOMESTIC,
        KT1,
        PROCESS_DATE,
        CASE_ID,
        VER,
        REPLACE_BY_ID,
        ORIGINAL_ID,
        CONTRACT_SERVICE_CODE,
        CUSTOMER_CODE_CRM,
        CUSTOMER_CODE_REF,
        BDT_CODE,
        DELIVERY_INSTRUCTION,
        IS_PRINT,
        CUSTOMER_TYPE,
        VERSION_LOCK,
        ISAUTOUPDATESENDER,
        IS_PACKAGE_NORMAL,
        IS_PUBLIC_POSTAL,
        DOCUMENT_TYPE,
        DOCUMENT_NAME,
        DOCUMENT_NUMBER,
        DOCUMENT_PROVIDE_DATE,
        DOCUMENT_PROVIDE_ADDRESS,
        SOURCE_SYSTEM,
        GROUP_TYPE,
        ORG_CODE_CREATE,
        USERNAME_CREATE,
        CUSTOMER_VPOSTCODE,
        CUSTOMER_LAT,
        CUSTOMER_LNG
    )
    VALUES (
        src.ID,
        src.CUSTOMER_CODE,
        src.CUSTOMER_NAME,
        src.CUSTOMER_PHONE,
        src.CUSTOMER_PROVINCE_CODE,
        src.CUSTOMER_DISTRICT_CODE,
        src.CUSTOMER_COMMUNE_CODE,
        src.CUSTOMER_POSTCODE,
        src.CUSTOMER_EMAIL,
        src.CUSTOMER_ADD,
        src.SHIPMENT_CODE,
        src.CUSTOMER_CONTRACT_NUMBER,
        src.CREATE_DATE,
        src.UPDATE_DATE,
        src.USERNAME,
        src.POCODE,
        src.STATUS,
        src.SOURCE,
        src.PAYNOW,
        src.PAYMENT,
        src.ORDER_CODE,
        src.ACCEPT_DATE,
        src.ISAUTOGEN,
        src.ISAUTOADD,
        src.ORG_CODE,
        src.BD2_NUM,
        src.CONTACT_NAME,
        src.TAX_CODE,
        src.IDENTIFY_NUM,
        src.TRANS_TYPE,
        src.ISDOMESTIC,
        src.KT1,
        src.PROCESS_DATE,
        src.CASE_ID,
        src.VER,
        src.REPLACE_BY_ID,
        src.ORIGINAL_ID,
        src.CONTRACT_SERVICE_CODE,
        src.CUSTOMER_CODE_CRM,
        src.CUSTOMER_CODE_REF,
        src.BDT_CODE,
        src.DELIVERY_INSTRUCTION,
        src.IS_PRINT,
        src.CUSTOMER_TYPE,
        src.VERSION_LOCK,
        src.ISAUTOUPDATESENDER,
        src.IS_PACKAGE_NORMAL,
        src.IS_PUBLIC_POSTAL,
        src.DOCUMENT_TYPE,
        src.DOCUMENT_NAME,
        src.DOCUMENT_NUMBER,
        src.DOCUMENT_PROVIDE_DATE,
        src.DOCUMENT_PROVIDE_ADDRESS,
        src.SOURCE_SYSTEM,
        src.GROUP_TYPE,
        src.ORG_CODE_CREATE,
        src.USERNAME_CREATE,
        src.CUSTOMER_VPOSTCODE,
        src.CUSTOMER_LAT,
        src.CUSTOMER_LNG
    );
