-- MERGE INTO pns.mail_route des
-- USING staging.pns_mail_route src
MERGE INTO {{ params.des_schema_name }}.{{ params.des_table_name }} des
USING staging.{{ params.des_schema_name }}_{{ params.des_table_name }} src
ON des.transport_number = src.transport_number
WHEN MATCHED THEN
    UPDATE
    SET transport_code = src.transport_code,
        transport_type = src.transport_type,
        transport_group = src.transport_group,
        capacity_register = src.capacity_register,
        capacity_min = src.capacity_min,
        capacity_max = src.capacity_max,
        payload_register = src.payload_register,
        payload_min = src.payload_min,
        payload_max = src.payload_max,
        lat = src.lat,
        long = src.long,
        gps_code = src.gps_code,
        gps_mobile_code = src.gps_mobile_code,
        contractor_code = src.contractor_code,
        contractor_name = src.contractor_name,
        note = src.note,
        temperature_min = src.temperature_min,
        temperature_max = src.temperature_max,
        connect_gps_status = src.connect_gps_status,
        is_unactive = src.is_unactive,
        is_lock = src.is_lock,
        driver_default = src.driver_default
WHEN NOT MATCHED THEN
    INSERT (transport_number,
            transport_code,
            transport_type,
            transport_group,
            capacity_register,
            capacity_min,
            capacity_max,
            payload_register,
            payload_min,
            payload_max,
            lat,
            long,
            gps_code,
            gps_mobile_code,
            contractor_code,
            contractor_name,
            note,
            temperature_min,
            temperature_max,
            connect_gps_status,
            is_unactive,
            is_lock,
            driver_default)
    VALUES (src.transport_number,
            src.transport_code,
            src.transport_type,
            src.transport_group,
            src.capacity_register,
            src.capacity_min,
            src.capacity_max,
            src.payload_register,
            src.payload_min,
            src.payload_max,
            src.lat,
            src.long,
            src.gps_code,
            src.gps_mobile_code,
            src.contractor_code,
            src.contractor_name,
            src.note,
            src.temperature_min,
            src.temperature_max,
            src.connect_gps_status,
            src.is_unactive,
            src.is_lock,
            src.driver_default)
