truncate table llb.d_service_product; 
insert into llb.d_service_product (
    row_item_code,
    row_item_name,
    nhom_chitieu,
    ma_spdv,
    ten_spdv,
    ma_nhom_spdv,
    ten_nhom_spdv,
    nuoc_phattra,
    pv_pv,
    dv_gtgt,
    is_gtg021,
    is_gtg038,
    is_gtg039,
    ngay_hl,
    ngay_kt
)
select
    row_item_code,
    row_item_name,
    nhom_chitieu,
    ma_spdv,
    ten_spdv,
    ma_nhom_spdv,
    ten_nhom_spdv,
    nuoc_phattra,
    pv_pv,
    dv_gtgt,
    is_gtg021,
    is_gtg038,
    is_gtg039,
    ngay_hl,
    ngay_kt
from
    llb.staging_d_service_product
