{% if dag_run.run_type == 'scheduled' %}
    {% set stg_table = "staging." ~ params.des_schema ~ "_" ~ params.des_table %}
{% else %}
    {% set stg_table = "staging." ~ params.des_schema ~ "_" ~ params.des_table ~ "_manual" %}
{% endif %}
MERGE INTO {{ params.des_schema }}.{{ params.des_table }} as des
USING 
  (
  SELECT 
    coalesce(item_code, '') as item_code,
   coalesce(acceptance_pos_code, '') AS acceptance_pos_code,
    sender_fullname,
    sender_address,
    customer_code,
    batch_code,
    receiver_fullname,
    receiver_tel,
    receiver_address,
    CASE WHEN is_domestic THEN B'1' ELSE B'0' END AS is_domestic,
    country_code,
    pos_code,
    CASE WHEN is_state_price THEN B'1' ELSE B'0' END AS is_stateprice,
    state_price_value,
    sending_content,
    note,
    item_type_code,
    sending_time,
    CASE WHEN is_airmail THEN B'1' ELSE B'0' END AS is_airmail,
    weight,
    status,
    total_freight,
    employee_code,
    sender_job,
    province_code,
    light_item,
    section_code,
    receiver_job,
    CASE WHEN is_opened THEN B'1' ELSE B'0' END AS is_opened,
    certificate_number,
    license_number,
    invoice_number,
    sender_identification,
    sender_issue_date,
    sender_issue_country,
    receiver_identification,
    receiver_issue_date,
    receiver_issue_country,
    sender_tel,
    main_freight,
    vat_freight,
    sub_freight,
    CASE WHEN is_post_free THEN B'1' ELSE B'0' END AS is_post_free,
    state_price_freight,
    printed_number,
    data_code,
    sender_custom_reference,
    remaining_freight,
    receiver_custom_reference,
    CASE WHEN is_return THEN B'1' ELSE B'0' END AS is_return,
    CASE WHEN is_compensate THEN B'1' ELSE B'0' END AS is_compensate,
    CASE WHEN is_forward THEN B'1' ELSE B'0' END AS is_forward,
    CASE WHEN is_airmail_forward THEN B'1' ELSE B'0' END AS is_airmail_forward,
    CASE WHEN is_airmail_return THEN B'1' ELSE B'0' END AS is_airmail_return,
    CASE WHEN is_debt THEN B'1' ELSE B'0' END AS is_debt,
    machine_name,
    accepted_index,
    bc16_index,
    incoming_index,
    service_code,
    receiver_district_code,
    letter_money_order_freight,
    value_added_service_freight_total_freight,
    order_code,
    sender_address_code,
    receiver_address_code,
    sender_mobile,
    sender_fax,
    sender_email,
    receiver_mobile,
    receiver_fax,
    receiver_email,
    discount,
    abatement,
    undeliverable_guide,
    width,
    height,
    length,
    check_sum,
    item_number,
    exchange_rate_code,
    cod_address,
    CASE WHEN cod_payment THEN B'1' ELSE B'0' END AS cod_payment,
    sender_district_code,
    receiver_contact,
    undeliverable_reason,
    decision_no,
    decision_date,
    return_day_number,
    discount_percentage,
    discount_amount,
    execute_order,
    CASE WHEN invoice_attached THEN B'1' ELSE B'0' END AS invoice_attached,
    CASE WHEN other_attached THEN B'1' ELSE B'0' END AS other_attached,
    other_attached_infor,
    transfer_machine,
    transfer_user,
    transfer_pos_code as transfer_poscode,
    transfer_date,
    CASE WHEN transfer_status THEN B'1' ELSE B'0' END AS transfer_status,
    transfer_times,
    weight_convert,
    CASE WHEN is_discount THEN B'1' ELSE B'0' END AS is_discount,
    CASE WHEN invoice_export THEN B'1' ELSE B'0' END AS invoice_export,
    total,
    accepted_type,
    sender_tax_code as sender_taxcode,
    vat_percentage,
    fuel_surcharge_freight,
    far_region_freight,
    air_surcharge_freight,
    other_freight,
    total_freight_vat,
    total_freight_discount,
    total_freight_discount_vat as total_freight_discountvat,
    receiver_tax_code,
    CASE WHEN far_region THEN B'1' ELSE B'0' END AS far_region,
    CASE WHEN is_collection THEN B'1' ELSE B'0' END AS is_collection,
    customer_account_no,
    CASE WHEN is_feedback THEN B'1' ELSE B'0' END AS is_feedback,
    feedback_percentage,
    feedback_amount,
    payment_freight,
    payment_freight_vat,
    payment_freight_discount,
    payment_freight_discount_vat,
    remaining_freight_vat,
    remaining_freight_discount,
    remaining_freight_discount_vat,
    CASE WHEN delivery_counter THEN B'1' ELSE B'0' END AS delivery_counter,
    advice_of_receipt_code,
    receiver_commune_code,
    check_content_on_delivery_code,
    destination_pos_code,
    CASE WHEN is_affair THEN B'1' ELSE B'0' END AS is_affair,
    return_before_date,
    customer_group_code,
    orther_freight,
    original_main_freight,
    original_sub_freight,
    original_fuel_surcharge_freight,
    original_far_region_freight,
    original_air_surcharge_freight,
    original_vat_freight,
    original_vat_percentage,
    original_total_freight,
    original_total_freight_vat,
    original_total_freight_discount,
    original_total_freight_discount_vat,
    original_payment_freight,
    original_payment_freight_vat,
    original_payment_freight_discount,
    original_payment_freight_discount_vat,
    original_remaining_freight,
    original_remaining_freight_vat,
    original_remaining_freight_discount,
    original_remaining_freight_discount_vat,
    CASE WHEN is_ecommerce THEN B'1' ELSE B'0' END AS is_ecommerce,
    create_time,
    last_updated_time,
    receiver_customer_code,
    delivery_note
  FROM {{ stg_table }}
  ) as src
ON des.item_code = src.item_code
WHEN MATCHED and des.last_updated_time < src.last_updated_time THEN
    UPDATE SET 
              item_code = src.item_code,
              acceptance_pos_code = src.acceptance_pos_code,
              sender_fullname = src.sender_fullname,
              sender_address = src.sender_address,
              customer_code = src.customer_code,
              batch_code = src.batch_code,
              receiver_fullname = src.receiver_fullname,
              receiver_tel = src.receiver_tel,
              receiver_address = src.receiver_address,
              is_domestic = src.is_domestic,
              country_code = src.country_code,
              pos_code = src.pos_code,
              is_stateprice = src.is_stateprice,
              state_price_value = src.state_price_value,
              sending_content = src.sending_content,
              note = src.note,
              item_type_code = src.item_type_code,
              sending_time = src.sending_time,
              is_airmail = src.is_airmail,
              weight = src.weight,
              status = src.status,
              total_freight = src.total_freight,
              employee_code = src.employee_code,
              sender_job = src.sender_job,
              province_code = src.province_code,
              light_item = src.light_item,
              section_code = src.section_code,
              receiver_job = src.receiver_job,
              is_opened = src.is_opened,
              certificate_number = src.certificate_number,
              license_number = src.license_number,
              invoice_number = src.invoice_number,
              sender_identification = src.sender_identification,
              sender_issue_date = src.sender_issue_date,
              sender_issue_country = src.sender_issue_country,
              receiver_identification = src.receiver_identification,
              receiver_issue_date = src.receiver_issue_date,
              receiver_issue_country = src.receiver_issue_country,
              sender_tel = src.sender_tel,
              main_freight = src.main_freight,
              vat_freight = src.vat_freight,
              sub_freight = src.sub_freight,
              is_post_free = src.is_post_free,
              state_price_freight = src.state_price_freight,
              printed_number = src.printed_number,
              data_code = src.data_code,
              sender_custom_reference = src.sender_custom_reference,
              remaining_freight = src.remaining_freight,
              receiver_custom_reference = src.receiver_custom_reference,
              is_return = src.is_return,
              is_compensate = src.is_compensate,
              is_forward = src.is_forward,
              is_airmail_forward = src.is_airmail_forward,
              is_airmail_return = src.is_airmail_return,
              is_debt = src.is_debt,
              machine_name = src.machine_name,
              accepted_index = src.accepted_index,
              bc16_index = src.bc16_index,
              incoming_index = src.incoming_index,
              service_code = src.service_code,
              receiver_district_code = src.receiver_district_code,
              letter_money_order_freight = src.letter_money_order_freight,
              value_added_service_freight_total_freight = src.value_added_service_freight_total_freight,
              order_code = src.order_code,
              sender_address_code = src.sender_address_code,
              receiver_address_code = src.receiver_address_code,
              sender_mobile = src.sender_mobile,
              sender_fax = src.sender_fax,
              sender_email = src.sender_email,
              receiver_mobile = src.receiver_mobile,
              receiver_fax = src.receiver_fax,
              receiver_email = src.receiver_email,
              discount = src.discount,
              abatement = src.abatement,
              undeliverable_guide = src.undeliverable_guide,
              width = src.width,
              height = src.height,
              length = src.length,
              check_sum = src.check_sum,
              item_number = src.item_number,
              exchange_rate_code = src.exchange_rate_code,
              cod_address = src.cod_address,
              cod_payment = src.cod_payment,
              sender_district_code = src.sender_district_code,
              receiver_contact = src.receiver_contact,
              undeliverable_reason = src.undeliverable_reason,
              decision_no = src.decision_no,
              decision_date = src.decision_date,
              return_day_number = src.return_day_number,
              discount_percentage = src.discount_percentage,
              discount_amount = src.discount_amount,
              execute_order = src.execute_order,
              invoice_attached = src.invoice_attached,
              other_attached = src.other_attached,
              other_attached_infor = src.other_attached_infor,
              transfer_machine = src.transfer_machine,
              transfer_user = src.transfer_user,
              transfer_poscode = src.transfer_poscode,
              transfer_date = src.transfer_date,
              transfer_status = src.transfer_status,
              transfer_times = src.transfer_times,
              weight_convert = src.weight_convert,
              is_discount = src.is_discount,
              invoice_export = src.invoice_export,
              total = src.total,
              accepted_type = src.accepted_type,
              sender_taxcode = src.sender_taxcode,
              vat_percentage = src.vat_percentage,
              fuel_surcharge_freight = src.fuel_surcharge_freight,
              far_region_freight = src.far_region_freight,
              air_surcharge_freight = src.air_surcharge_freight,
              other_freight = src.other_freight,
              total_freight_vat = src.total_freight_vat,
              total_freight_discount = src.total_freight_discount,
              total_freight_discountvat = src.total_freight_discountvat,
              receiver_tax_code = src.receiver_tax_code,
              far_region = src.far_region,
              is_collection = src.is_collection,
              customer_account_no = src.customer_account_no,
              is_feedback = src.is_feedback,
              feedback_percentage = src.feedback_percentage,
              feedback_amount = src.feedback_amount,
              payment_freight = src.payment_freight,
              payment_freight_vat = src.payment_freight_vat,
              payment_freight_discount = src.payment_freight_discount,
              payment_freight_discount_vat = src.payment_freight_discount_vat,
              remaining_freight_vat = src.remaining_freight_vat,
              remaining_freight_discount = src.remaining_freight_discount,
              remaining_freight_discount_vat = src.remaining_freight_discount_vat,
              delivery_counter = src.delivery_counter,
              advice_of_receipt_code = src.advice_of_receipt_code,
              receiver_commune_code = src.receiver_commune_code,
              check_content_on_delivery_code = src.check_content_on_delivery_code,
              destination_pos_code = src.destination_pos_code,
              is_affair = src.is_affair,
              return_before_date = src.return_before_date,
              customer_group_code = src.customer_group_code,
              orther_freight = src.orther_freight,
              original_main_freight = src.original_main_freight,
              original_sub_freight = src.original_sub_freight,
              original_fuel_surcharge_freight = src.original_fuel_surcharge_freight,
              original_far_region_freight = src.original_far_region_freight,
              original_air_surcharge_freight = src.original_air_surcharge_freight,
              original_vat_freight = src.original_vat_freight,
              original_vat_percentage = src.original_vat_percentage,
              original_total_freight = src.original_total_freight,
              original_total_freight_vat = src.original_total_freight_vat,
              original_total_freight_discount = src.original_total_freight_discount,
              original_total_freight_discount_vat = src.original_total_freight_discount_vat,
              original_payment_freight = src.original_payment_freight,
              original_payment_freight_vat = src.original_payment_freight_vat,
              original_payment_freight_discount = src.original_payment_freight_discount,
              original_payment_freight_discount_vat = src.original_payment_freight_discount_vat,
              original_remaining_freight = src.original_remaining_freight,
              original_remaining_freight_vat = src.original_remaining_freight_vat,
              original_remaining_freight_discount = src.original_remaining_freight_discount,
              original_remaining_freight_discount_vat = src.original_remaining_freight_discount_vat,
              is_ecommerce = src.is_ecommerce,
              create_time = src.create_time,
              last_updated_time = src.last_updated_time,
              receiver_customer_code = src.receiver_customer_code,
              delivery_note = src.delivery_note
WHEN NOT MATCHED THEN
    INSERT (
      item_code,
      acceptance_pos_code,
      sender_fullname,
      sender_address,
      customer_code,
      batch_code,
      receiver_fullname,
      receiver_tel,
      receiver_address,
      is_domestic,
      country_code,
      pos_code,
      is_stateprice,
      state_price_value,
      sending_content,
      note,
      item_type_code,
      sending_time,
      is_airmail,
      weight,
      status,
      total_freight,
      employee_code,
      sender_job,
      province_code,
      light_item,
      section_code,
      receiver_job,
      is_opened,
      certificate_number,
      license_number,
      invoice_number,
      sender_identification,
      sender_issue_date,
      sender_issue_country,
      receiver_identification,
      receiver_issue_date,
      receiver_issue_country,
      sender_tel,
      main_freight,
      vat_freight,
      sub_freight,
      is_post_free,
      state_price_freight,
      printed_number,
      data_code,
      sender_custom_reference,
      remaining_freight,
      receiver_custom_reference,
      is_return,
      is_compensate,
      is_forward,
      is_airmail_forward,
      is_airmail_return,
      is_debt,
      machine_name,
      accepted_index,
      bc16_index,
      incoming_index,
      service_code,
      receiver_district_code,
      letter_money_order_freight,
      value_added_service_freight_total_freight,
      order_code,
      sender_address_code,
      receiver_address_code,
      sender_mobile,
      sender_fax,
      sender_email,
      receiver_mobile,
      receiver_fax,
      receiver_email,
      discount,
      abatement,
      undeliverable_guide,
      width,
      height,
      length,
      check_sum,
      item_number,
      exchange_rate_code,
      cod_address,
      cod_payment,
      sender_district_code,
      receiver_contact,
      undeliverable_reason,
      decision_no,
      decision_date,
      return_day_number,
      discount_percentage,
      discount_amount,
      execute_order,
      invoice_attached,
      other_attached,
      other_attached_infor,
      transfer_machine,
      transfer_user,
      transfer_poscode,
      transfer_date,
      transfer_status,
      transfer_times,
      weight_convert,
      is_discount,
      invoice_export,
      total,
      accepted_type,
      sender_taxcode,
      vat_percentage,
      fuel_surcharge_freight,
      far_region_freight,
      air_surcharge_freight,
      other_freight,
      total_freight_vat,
      total_freight_discount,
      total_freight_discountvat,
      receiver_tax_code,
      far_region,
      is_collection,
      customer_account_no,
      is_feedback,
      feedback_percentage,
      feedback_amount,
      payment_freight,
      payment_freight_vat,
      payment_freight_discount,
      payment_freight_discount_vat,
      remaining_freight_vat,
      remaining_freight_discount,
      remaining_freight_discount_vat,
      delivery_counter,
      advice_of_receipt_code,
      receiver_commune_code,
      check_content_on_delivery_code,
      destination_pos_code,
      is_affair,
      return_before_date,
      customer_group_code,
      orther_freight,
      original_main_freight,
      original_sub_freight,
      original_fuel_surcharge_freight,
      original_far_region_freight,
      original_air_surcharge_freight,
      original_vat_freight,
      original_vat_percentage,
      original_total_freight,
      original_total_freight_vat,
      original_total_freight_discount,
      original_total_freight_discount_vat,
      original_payment_freight,
      original_payment_freight_vat,
      original_payment_freight_discount,
      original_payment_freight_discount_vat,
      original_remaining_freight,
      original_remaining_freight_vat,
      original_remaining_freight_discount,
      original_remaining_freight_discount_vat,
      is_ecommerce,
      create_time,
      last_updated_time,
      receiver_customer_code,
      delivery_note
    )VALUES(
      src.item_code,
      src.acceptance_pos_code,
      src.sender_fullname,
      src.sender_address,
      src.customer_code,
      src.batch_code,
      src.receiver_fullname,
      src.receiver_tel,
      src.receiver_address,
      src.is_domestic,
      src.country_code,
      src.pos_code,
      src.is_stateprice,
      src.state_price_value,
      src.sending_content,
      src.note,
      src.item_type_code,
      src.sending_time,
      src.is_airmail,
      src.weight,
      src.status,
      src.total_freight,
      src.employee_code,
      src.sender_job,
      src.province_code,
      src.light_item,
      src.section_code,
      src.receiver_job,
      src.is_opened,
      src.certificate_number,
      src.license_number,
      src.invoice_number,
      src.sender_identification,
      src.sender_issue_date,
      src.sender_issue_country,
      src.receiver_identification,
      src.receiver_issue_date,
      src.receiver_issue_country,
      src.sender_tel,
      src.main_freight,
      src.vat_freight,
      src.sub_freight,
      src.is_post_free,
      src.state_price_freight,
      src.printed_number,
      src.data_code,
      src.sender_custom_reference,
      src.remaining_freight,
      src.receiver_custom_reference,
      src.is_return,
      src.is_compensate,
      src.is_forward,
      src.is_airmail_forward,
      src.is_airmail_return,
      src.is_debt,
      src.machine_name,
      src.accepted_index,
      src.bc16_index,
      src.incoming_index,
      src.service_code,
      src.receiver_district_code,
      src.letter_money_order_freight,
      src.value_added_service_freight_total_freight,
      src.order_code,
      src.sender_address_code,
      src.receiver_address_code,
      src.sender_mobile,
      src.sender_fax,
      src.sender_email,
      src.receiver_mobile,
      src.receiver_fax,
      src.receiver_email,
      src.discount,
      src.abatement,
      src.undeliverable_guide,
      src.width,
      src.height,
      src.length,
      src.check_sum,
      src.item_number,
      src.exchange_rate_code,
      src.cod_address,
      src.cod_payment,
      src.sender_district_code,
      src.receiver_contact,
      src.undeliverable_reason,
      src.decision_no,
      src.decision_date,
      src.return_day_number,
      src.discount_percentage,
      src.discount_amount,
      src.execute_order,
      src.invoice_attached,
      src.other_attached,
      src.other_attached_infor,
      src.transfer_machine,
      src.transfer_user,
      src.transfer_poscode,
      src.transfer_date,
      src.transfer_status,
      src.transfer_times,
      src.weight_convert,
      src.is_discount,
      src.invoice_export,
      src.total,
      src.accepted_type,
      src.sender_taxcode,
      src.vat_percentage,
      src.fuel_surcharge_freight,
      src.far_region_freight,
      src.air_surcharge_freight,
      src.other_freight,
      src.total_freight_vat,
      src.total_freight_discount,
      src.total_freight_discountvat,
      src.receiver_tax_code,
      src.far_region,
      src.is_collection,
      src.customer_account_no,
      src.is_feedback,
      src.feedback_percentage,
      src.feedback_amount,
      src.payment_freight,
      src.payment_freight_vat,
      src.payment_freight_discount,
      src.payment_freight_discount_vat,
      src.remaining_freight_vat,
      src.remaining_freight_discount,
      src.remaining_freight_discount_vat,
      src.delivery_counter,
      src.advice_of_receipt_code,
      src.receiver_commune_code,
      src.check_content_on_delivery_code,
      src.destination_pos_code,
      src.is_affair,
      src.return_before_date,
      src.customer_group_code,
      src.orther_freight,
      src.original_main_freight,
      src.original_sub_freight,
      src.original_fuel_surcharge_freight,
      src.original_far_region_freight,
      src.original_air_surcharge_freight,
      src.original_vat_freight,
      src.original_vat_percentage,
      src.original_total_freight,
      src.original_total_freight_vat,
      src.original_total_freight_discount,
      src.original_total_freight_discount_vat,
      src.original_payment_freight,
      src.original_payment_freight_vat,
      src.original_payment_freight_discount,
      src.original_payment_freight_discount_vat,
      src.original_remaining_freight,
      src.original_remaining_freight_vat,
      src.original_remaining_freight_discount,
      src.original_remaining_freight_discount_vat,
      src.is_ecommerce,
      src.create_time,
      src.last_updated_time,
      src.receiver_customer_code,
      src.delivery_note
    )
