{% if dag_run.run_type == 'scheduled' %}
    {% set stg_table = "staging." ~ params.des_schema ~ "_" ~ params.des_table %}
{% else %}
    {% set stg_table = "staging." ~ params.des_schema ~ "_" ~ params.des_table ~ "_manual" %}
{% endif %}
MERGE INTO {{ params.des_schema }}.{{ params.des_table }} as des
USING (
  SELECT 
        delivery_index,
        coalesce(to_pos_code, '') AS to_pos_code,
        coalesce(item_code, '')  AS item_code,
        cause_code,
        solution_code,
        delivery_date,
        delivery_certificate_name,
        delivery_certificate_number,
        delivery_certificate_date_of_issue,
        delivery_certificate_place_of_issue,
        CASE WHEN is_deliverable THEN B'1' ELSE B'0' END AS is_deliverable,
        delivery_note,
        real_reciver_name,
        real_receiver_identification,
        delivery_machine,
        delivery_user,
        inputing_user,
        returning_money,
        returning_money_date,
        collection_money,
        collection_money_date,
        transfer_machine,
        transfer_user,
        transfer_pos_code,
        transfer_date,
        CASE WHEN transfer_status THEN B'1' ELSE B'0' END AS transfer_status,
        transfer_times,
        input_date,
        CASE WHEN send_mail_success THEN B'1' ELSE B'0' END AS send_mail_success,
        send_mail_date,
        CASE WHEN send_sms_success THEN B'1' ELSE B'0' END AS send_sms_success,
        send_sms_date,
        cod_amount,
        cod_freight,
        postage_freight,
        added_freight,
        return_freight,
        other_freight,
        delivery_certificate_other_name,
        object_transfer,
        CASE WHEN delivery_return THEN B'1' ELSE B'0' END AS delivery_return,
        create_time,
        last_updated_time,
        handover_index,
        shift_code,
        counter_code,
        pos_code,
        postman_code,
        postman_name,
        delivery_route_code,
        delivery_route_name,
        delivery_transfer_id
  FROM {{ stg_table }}
  ) as src
ON des.delivery_index = src.delivery_index 
  and des.to_pos_code = src.to_pos_code
  and des.item_code = src.item_code and des.delivery_date =src.delivery_date
WHEN MATCHED and des.last_updated_time < src.last_updated_time THEN
    UPDATE SET 
      cause_code = src.cause_code,
      solution_code = src.solution_code,
      delivery_date = src.delivery_date,
      delivery_certificate_name = src.delivery_certificate_name,
      delivery_certificate_number = src.delivery_certificate_number,
      delivery_certificate_date_of_issue = src.delivery_certificate_date_of_issue,
      delivery_certificate_place_of_issue = src.delivery_certificate_place_of_issue,
      is_deliverable = src.is_deliverable,
      delivery_note = src.delivery_note,
      real_reciver_name = src.real_reciver_name,
      real_receiver_identification = src.real_receiver_identification,
      delivery_machine = src.delivery_machine,
      delivery_user = src.delivery_user,
      inputing_user = src.inputing_user,
      returning_money = src.returning_money,
      returning_money_date = src.returning_money_date,
      collection_money = src.collection_money,
      collection_money_date = src.collection_money_date,
      transfer_machine = src.transfer_machine,
      transfer_user = src.transfer_user,
      transfer_pos_code = src.transfer_pos_code,
      transfer_date = src.transfer_date,
      transfer_status = src.transfer_status,
      transfer_times = src.transfer_times,
      input_date = src.input_date,
      send_mail_success = src.send_mail_success,
      send_mail_date = src.send_mail_date,
      send_sms_success = src.send_sms_success,
      send_sms_date = src.send_sms_date,
      cod_amount = src.cod_amount,
      cod_freight = src.cod_freight,
      postage_freight = src.postage_freight,
      added_freight = src.added_freight,
      return_freight = src.return_freight,
      other_freight = src.other_freight,
      delivery_certificate_other_name = src.delivery_certificate_other_name,
      object_transfer = src.object_transfer,
      delivery_return = src.delivery_return,
      create_time = src.create_time,
      last_updated_time = src.last_updated_time,
      handover_index = src.handover_index,
      shift_code = src.shift_code,
      counter_code = src.counter_code,
      pos_code = src.pos_code,
      postman_code = src.postman_code,
      postman_name = src.postman_name,
      delivery_route_code = src.delivery_route_code,
      delivery_route_name = src.delivery_route_name,
      delivery_transfer_id = src.delivery_transfer_id
WHEN NOT MATCHED THEN
      INSERT (
        delivery_index,
        to_pos_code,
        item_code,
        cause_code,
        solution_code,
        delivery_date,
        delivery_certificate_name,
        delivery_certificate_number,
        delivery_certificate_date_of_issue,
        delivery_certificate_place_of_issue,
        is_deliverable,
        delivery_note,
        real_reciver_name,
        real_receiver_identification,
        delivery_machine,
        delivery_user,
        inputing_user,
        returning_money,
        returning_money_date,
        collection_money,
        collection_money_date,
        transfer_machine,
        transfer_user,
        transfer_pos_code,
        transfer_date,
        transfer_status,
        transfer_times,
        input_date,
        send_mail_success,
        send_mail_date,
        send_sms_success,
        send_sms_date,
        cod_amount,
        cod_freight,
        postage_freight,
        added_freight,
        return_freight,
        other_freight,
        delivery_certificate_other_name,
        object_transfer,
        delivery_return,
        create_time,
        last_updated_time,
        handover_index,
        shift_code,
        counter_code,
        pos_code,
        postman_code,
        postman_name,
        delivery_route_code,
        delivery_route_name,
        delivery_transfer_id
      ) VALUES (
        src.delivery_index,
        src.to_pos_code,
        src.item_code,
        src.cause_code,
        src.solution_code,
        src.delivery_date,
        src.delivery_certificate_name,
        src.delivery_certificate_number,
        src.delivery_certificate_date_of_issue,
        src.delivery_certificate_place_of_issue,
        src.is_deliverable,
        src.delivery_note,
        src.real_reciver_name,
        src.real_receiver_identification,
        src.delivery_machine,
        src.delivery_user,
        src.inputing_user,
        src.returning_money,
        src.returning_money_date,
        src.collection_money,
        src.collection_money_date,
        src.transfer_machine,
        src.transfer_user,
        src.transfer_pos_code,
        src.transfer_date,
        src.transfer_status,
        src.transfer_times,
        src.input_date,
        src.send_mail_success,
        src.send_mail_date,
        src.send_sms_success,
        src.send_sms_date,
        src.cod_amount,
        src.cod_freight,
        src.postage_freight,
        src.added_freight,
        src.return_freight,
        src.other_freight,
        src.delivery_certificate_other_name,
        src.object_transfer,
        src.delivery_return,
        src.create_time,
        src.last_updated_time,
        src.handover_index,
        src.shift_code,
        src.counter_code,
        src.pos_code,
        src.postman_code,
        src.postman_name,
        src.delivery_route_code,
        src.delivery_route_name,
        src.delivery_transfer_id
      )
