DECLARE @StartTime DATETIME = CONVERT(DATETIME,'{{ params.start_time }}', 120);
DECLARE @EndTime DATETIME = CONVERT(DATETIME,'{{ params.end_time }}', 120);

SELECT ItemCode ,
      AcceptancePOSCode ,
      SenderFullname ,
     ''  SenderAddress ,
      CustomerCode ,
      BatchCode ,
      ReceiverFullname ,
     ''  ReceiverTel ,
     ''  ReceiverAddress ,
      isDomestic ,
      CountryCode ,
      POSCode ,
      IsStatePrice ,
      StatePriceValue ,
      SendingContent ,
      Note ,
      ItemTypeCode ,
      SendingTime ,
      IsAirmail ,
      Weight ,
      Status ,
      TotalFreight ,
      EmployeeCode ,
      SenderJob ,
      ProvinceCode ,
      LightItem ,
      SectionCode ,
      ReceiverJob ,
      IsOpened ,
      CertificateNumber ,
      LicenseNumber ,
      InvoiceNumber ,
      SenderIdentification ,
      SenderIssueDate ,
      SenderIssueCountry ,
      ReceiverIdentification ,
      ReceiverIssueDate ,
      ReceiverIssueCountry ,
      SenderTel ,
      MainFreight ,
      VATFreight ,
      SubFreight ,
      IsPostFree ,
      StatePriceFreight ,
      PrintedNumber ,
      DataCode ,
      SenderCustomReference ,
      RemainingFreight ,
      ReceiverCustomReference ,
      IsReturn ,
      IsCompensate ,
      IsForward ,
      IsAirmailForward ,
      IsAirmailReturn ,
      IsDebt ,
      MachineName ,
      AcceptedIndex ,
      BC16Index ,
      IncomingIndex ,
      ServiceCode ,
      ReceiverDistrictCode ,
      LetterMoneyOrderFreight ,
      ValueAddedServiceFreightTotalFreight ,
      OrderCode ,
     '' SenderAddressCode ,
     '' ReceiverAddressCode ,
     '' SenderMobile ,
     '' SenderFax ,
     '' SenderEmail ,
     '' ReceiverMobile ,
     '' ReceiverFax ,
     '' ReceiverEmail ,
      Discount ,
      Abatement ,
      UndeliverableGuide ,
      Width ,
      Height ,
      Length ,
      CheckSum ,
      ItemNumber ,
      ExchangeRateCode ,
      CODAddress ,
      CODPayment ,
      SenderDistrictCode ,
     '' ReceiverContact ,
      UndeliverableReason ,
      DecisionNo ,
      DecisionDate ,
      ReturnDayNumber ,
      DiscountPercentage ,
      DiscountAmount ,
      ExecuteOrder ,
      InvoiceAttached ,
      OtherAttached ,
      OtherAttachedInfor ,
      TransferMachine ,
      TransferUser ,
      TransferPOSCode ,
      TransferDate ,
      TransferStatus ,
      TransferTimes ,
      WeightConvert ,
      IsDiscount ,
      InvoiceExport ,
      Total ,
      AcceptedType ,
      SenderTaxCode ,
      VATPercentage ,
      FuelSurchargeFreight ,
      FarRegionFreight ,
      AirSurchargeFreight ,
      OtherFreight ,
      TotalFreightVAT ,
      TotalFreightDiscount ,
      TotalFreightDiscountVAT ,
      ReceiverTaxCode ,
      FarRegion ,
      IsCollection ,
      CustomerAccountNo ,
      IsFeedback ,
      FeedbackPercentage ,
      FeedbackAmount ,
      PaymentFreight ,
      PaymentFreightVAT ,
      PaymentFreightDiscount ,
      PaymentFreightDiscountVAT ,
      RemainingFreightVAT ,
      RemainingFreightDiscount ,
      RemainingFreightDiscountVAT ,
      DeliveryCounter ,
      AdviceOfReceiptCode ,
      ReceiverCommuneCode ,
      CheckContentOnDeliveryCode ,
      DestinationPOSCode ,
      IsAffair ,
      ReturnBeforeDate ,
      CustomerGroupCode ,
      OrtherFreight ,
      OriginalMainFreight ,
      OriginalSubFreight ,
      OriginalFuelSurchargeFreight ,
      OriginalFarRegionFreight ,
      OriginalAirSurchargeFreight ,
      OriginalVatFreight ,
      OriginalVATPercentage ,
      OriginalTotalFreight ,
      OriginalTotalFreightVAT ,
      OriginalTotalFreightDiscount ,
      OriginalTotalFreightDiscountVAT ,
      OriginalPaymentFreight ,
      OriginalPaymentFreightVAT ,
      OriginalPaymentFreightDiscount ,
      OriginalPaymentFreightDiscountVAT ,
      OriginalRemainingFreight ,
      OriginalRemainingFreightVAT ,
      OriginalRemainingFreightDiscount ,
      OriginalRemainingFreightDiscountVAT ,
      IsEcommerce ,
      CreateTime ,
      LastUpdatedTime ,
      ReceiverCustomerCode ,
      DeliveryNote
FROM {{ params.src_schema }}.{{ params.src_table }}
WHERE LastUpdatedTime >= @StartTime
  AND LastUpdatedTime < @EndTime;
