DECLARE @StartTime DATETIME = CONVERT(DATETIME,'{{ params.start_time }}', 120);
DECLARE @EndTime DATETIME = CONVERT(DATETIME,'{{ params.end_time }}', 120);

SELECT  DeliveryIndex ,
        ToPOSCode ,
        ItemCode ,
        CauseCode ,
        SolutionCode ,
        DeliveryDate ,
        DeliveryCertificateName ,
        DeliveryCertificateNumber ,
        DeliveryCertificateDateOfIssue ,
        DeliveryCertificatePlaceOfIssue ,
        IsDeliverable ,
        DeliveryNote ,
        RealReciverName ,
        RealReceiverIdentification ,
        DeliveryMachine ,
        DeliveryUser ,
        InputingUser ,
        ReturningMoney ,
        ReturningMoneyDate ,
        CollectionMoney ,
        CollectionMoneyDate ,
        TransferMachine ,
        TransferUser ,
        TransferPOSCode ,
        TransferDate ,
        TransferStatus ,
        TransferTimes ,
        InputDate ,
        SendMailSuccess ,
        SendMailDate ,
        SendSMSSuccess ,
        SendSMSDate ,
        CODAmount ,
        CODFreight ,
        PostageFreight ,
        AddedFreight ,
        ReturnFreight ,
        OtherFreight ,
        DeliveryCertificateOtherName ,
        ObjectTransfer ,
        DeliveryReturn ,
        CreateTime ,
        LastUpdatedTime ,
        HandoverIndex ,
        ShiftCode ,
        CounterCode ,
        POSCode ,
        PostmanCode ,
        PostmanName ,
        DeliveryRouteCode ,
        DeliveryRouteName ,
        DeliveryTransferID
FROM {{ params.src_schema }}.{{ params.src_table }}
WHERE  LastUpdatedTime >= @StartTime
  AND LastUpdatedTime < @EndTime;
